name: branch builder

on:
  push:
    branches:
      - '*'
      - '!master'
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .
