name: image build and push

on:
  push:
    branches: master
    paths-ignore:
      - '**.md'
  schedule:
    - cron: "0 4 */8 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        run: |
          docker build --tag mehmetahsen/stoken:latest --tag mehmetahsen/stoken:${{ github.sha }} .
          docker push mehmetahsen/stoken:latest
          docker push mehmetahsen/stoken:${{ github.sha }}
